// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  renderReportPdf: {
    request: z.object({ templateInput: z.any() }),
    response: z.object({ pdfBase64: z.string().min(1), renderer: z.string() }),
    timeoutMs: 120000,
  },
  renderHtmlPdf: {
    request: z.object({ html: z.string().min(1) }),
    response: z.object({ pdfBase64: z.string().min(1), renderer: z.string() }),
    timeoutMs: 120000,
  },
  loadLegacySmtpConfiguration: {
    request: z.object({}),
    response: z.object({ found: z.boolean(), host: z.string(), user: z.string(), password: z.string(), port: z.number().int(), fromEmail: z.string(), fromName: z.string() }),
  },
  sendSmtpMail: {
    request: z.object({ host: z.string().min(1), user: z.string().min(1), password: z.string().min(1), port: z.number().int().min(1).max(65535), fromEmail: z.string().email(), fromName: z.string().min(1), to: z.string().email(), subject: z.string().min(1), html: z.string().min(1) }),
    response: z.object({ ok: z.boolean(), usedPort: z.number().int(), messageId: z.string().optional(), error: z.string().optional() }),
    timeoutMs: 30000,
  },
});
