INSERT OR IGNORE INTO `email_templates` (`template_key`,`name`,`subject`,`preheader`,`heading`,`body_html`,`button_label`,`button_url`,`image_url`,`brand_primary`,`brand_accent`,`updated_at`) VALUES
('upgrade_1','Snapshot upgrade 1','Go beyond your snapshot, {{first_name}}','Your next level of capability insight is ready.','Your snapshot is the beginning','<p>Hi {{first_name}},</p><p>Your free snapshot showed the pattern across your five LEADS pillars. The Full Assessment goes further with the complete 93-question experience, capability-level detail, career benchmarks, industry best-fit, learning recommendations, and the full career toolkit.</p><p>When you are ready for a more complete picture, your next step is waiting.</p>','Explore the Full Assessment','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000),
('upgrade_2','Snapshot upgrade 2','Save 25% on your Full Assessment','Use UPGRADE25 to move beyond your free snapshot.','A clearer picture, now 25% off','<p>Hi {{first_name}},</p><p>Your snapshot identified the broad themes. The Full Assessment helps you see the capabilities inside each pillar and gives you practical tools for your next career move.</p><p>Use code <strong>UPGRADE25</strong> at checkout to save 25% on the Full Assessment.</p>','Use UPGRADE25','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000),
('upgrade_3','Snapshot upgrade 3','Your 25% upgrade offer is still available','UPGRADE25 is ready when you want deeper insight.','Turn your snapshot into a complete evidence map','<p>Hi {{first_name}},</p><p>Your five-pillar snapshot is a useful starting point. The complete assessment adds the detail you need to explain your strengths with greater confidence.</p><p>Enter <strong>UPGRADE25</strong> at checkout for 25% off the Full Assessment.</p>','Upgrade with 25% off','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000),
('upgrade_4','Snapshot upgrade 4','A 50% Full Assessment offer for you','Use UPGRADE50 for your biggest upgrade saving.','Go deeper for half the price','<p>Hi {{first_name}},</p><p>If you want more than a directional snapshot, this is a strong time to continue. The Full Assessment gives you the complete question set, detailed report, benchmarks, best-fit insights, learning recommendations, and career toolkit.</p><p>Use code <strong>UPGRADE50</strong> at checkout to save 50% on the Full Assessment.</p>','Use UPGRADE50','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000),
('upgrade_5','Snapshot upgrade 5','Your 50% Full Assessment offer is waiting','UPGRADE50 is still available.','Build the evidence behind your next move','<p>Hi {{first_name}},</p><p>The strongest career decisions start with evidence. Your Full Assessment can reveal the detailed capability pattern behind the five pillars in your snapshot.</p><p>Use <strong>UPGRADE50</strong> at checkout for 50% off.</p>','Upgrade with 50% off','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000),
('upgrade_6','Snapshot upgrade 6','Last chance to use your 50% upgrade offer','A final reminder about UPGRADE50.','One final chance to complete the picture','<p>Hi {{first_name}},</p><p>This is your final reminder to move from the free snapshot to the Full Assessment at 50% off.</p><p>Use code <strong>UPGRADE50</strong> at checkout to unlock the complete assessment, detailed report, and career toolkit.</p>','Use UPGRADE50','https://app.orginsights.io/',NULL,'#075d46','#a9ddc5',1791295944000);
--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`,`value`,`updated_at`) VALUES
('upgrade_email_1_delay_days','1',1791295944000),
('upgrade_email_2_delay_days','3',1791295944000),
('upgrade_email_3_delay_days','4',1791295944000),
('upgrade_email_4_delay_days','7',1791295944000),
('upgrade_email_5_delay_days','7',1791295944000),
('upgrade_email_6_delay_days','7',1791295944000);